version: '3.4'
services:
  web:
    container_name: webapi
    image: app:latest
    build:
      dockerfile: src\api\Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

